version: "3"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - forfardata:/var/lib/postgresql/data/
    network_mode: host
  redis:
    image: redis
    network_mode: host
  wkhtmltopdf:
    image: openlabs/docker-wkhtmltopdf-aas
    network_mode: host
volumes:
  forfardata:
