version: "3"
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - forfardata:/var/lib/postgresql/data/
    network_mode: host
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: host

  # web:
  #   build:
  #     context: ./test1
  #   restart: always
  #   command: python3 /code/manage.py runserver 0.0.0.0:8000
  #   volumes:
  #     - ./test1:/code/
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     SECRET_KEY: bigsecretkey
  #     DJANGO_CONFIGURATION: Develop
  #     DJANGO_SETTINGS_MODULE: "test1.settings_compose"
  #     DEBUG: 'true'
  #     API_PG_USER: postgres
  #     API_PG_PASSWORD: postgres
  #     API_PG_DB: postgres
  #     API_PG_HOST: db
  #     API_PG_PORT: 5432
  #   depends_on:
  #     - db
volumes:
  forfardata:
