# Generated by Django 3.2 on 2022-05-26 10:35

from django.db import migrations, models
import django.db.models.deletion
import receipt.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование принтера')),
                ('api_key', models.CharField(max_length=32, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(max_length=10, verbose_name='Тип чека')),
                ('point_id', models.IntegerField(verbose_name='Идентификатор точки')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
                'db_table': 'printers',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(max_length=10, verbose_name='Тип чека')),
                ('order', models.JSONField(verbose_name='Информация о заказе')),
                ('status', models.CharField(max_length=10, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=receipt.models.Check.files_directory_path)),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipt.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
                'db_table': 'checks',
                'ordering': ['-id'],
            },
        ),
    ]
