# Generated by Django 3.2 on 2022-05-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0002_rename_check_type_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(max_length=32, unique=True, verbose_name='Ключ доступа к API'),
        ),
    ]
